/**
 * Browser/server feature parity (milestone M2).
 *
 * The claim is that the in-browser detector reproduces the server's. That was
 * demonstrated by opening /lab/parity and reading a table -- which proves it on
 * the day someone looks, and says nothing about the day after.
 *
 * Here the server's own feature vectors are loaded from a fixture generated by
 * scripts/generate_feature_parity_fixture.py and compared against what
 * app/static/js/tamper-onnx.js computes from the identical bytes. Drift in
 * either implementation fails the build.
 *
 * The tolerance is tight on purpose. These are not two approximations of the
 * same idea; they are the same arithmetic, and the only expected difference is
 * float64 association order. A feature that moves by more than a part in 10^9
 * has changed, not rounded.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { STATIC_JS, loadBrowserScript, makeWindow } from './harness.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE = resolve(HERE, 'fixtures', 'feature-parity.json');

const RELATIVE_TOLERANCE = 1e-9;
// Features that are legitimately near zero (correlations on flat images) need an
// absolute floor, or a relative comparison against 0.0 divides by nothing.
const ABSOLUTE_FLOOR = 1e-9;

const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8'));

const window = makeWindow();
loadBrowserScript(join(STATIC_JS, 'tamper-onnx.js'), { window, console, self: window });
const { extractFeatures, FEATURE_NAMES } = window.revealxTamperInternals;

function close(actual, expected) {
    if (Number.isNaN(actual) && Number.isNaN(expected)) return true;
    const scale = Math.max(Math.abs(expected), ABSOLUTE_FLOOR);
    return Math.abs(actual - expected) / scale <= RELATIVE_TOLERANCE;
}

test('the browser and the server agree on the feature list', () => {
    assert.deepEqual(FEATURE_NAMES, fixture.featureNames);
});

test('the fixture covers the cases worth covering', () => {
    // A fixture that silently shrank to one easy case would keep passing.
    assert.ok(fixture.cases.length >= 10, 'at least ten cases');
    const names = fixture.cases.map((c) => c.name);
    for (const required of ['flat-mid', 'checkerboard', 'ragged-70x53', 'gradient']) {
        assert.ok(names.includes(required), `covers ${required}`);
    }
});

for (const testCase of fixture.cases) {
    test(`features match the server: ${testCase.name}`, () => {
        const gray = new Uint8Array(Buffer.from(testCase.pixels, 'base64'));
        assert.equal(gray.length, testCase.width * testCase.height, 'fixture pixel count');

        const actual = extractFeatures(gray, testCase.width, testCase.height);
        assert.equal(actual.length, testCase.features.length);

        const drift = [];
        for (let i = 0; i < actual.length; i++) {
            if (!close(actual[i], testCase.features[i])) {
                drift.push(
                    `${FEATURE_NAMES[i]}: browser ${actual[i]} vs server ${testCase.features[i]}`
                );
            }
        }
        assert.deepEqual(drift, [], `feature drift in ${testCase.name}`);
    });
}

test('every feature is finite, on every case', () => {
    // A NaN propagates into the model as a silent misclassification rather than
    // an error, so it must not be possible to produce one at all.
    for (const testCase of fixture.cases) {
        const gray = new Uint8Array(Buffer.from(testCase.pixels, 'base64'));
        const features = extractFeatures(gray, testCase.width, testCase.height);
        features.forEach((value, i) => {
            assert.ok(
                Number.isFinite(value),
                `${testCase.name}/${FEATURE_NAMES[i]} was ${value}`
            );
        });
    }
});

test('a colour source is refused rather than approximated', () => {
    // Decoding colour to grayscale in the browser does not reproduce what the
    // server's libpng path produces -- it was off by one on about 0.3% of
    // pixels. Refusing and deferring to the server is the correct answer; a
    // "close enough" conversion here would make the parity claim false.
    const { toGrayscale } = window.revealxTamperInternals;

    const colour = { width: 2, height: 1, data: new Uint8ClampedArray([10, 20, 30, 255, 40, 40, 40, 255]) };
    assert.equal(toGrayscale(colour).exact, false, 'colour input is flagged inexact');

    const grey = { width: 2, height: 1, data: new Uint8ClampedArray([77, 77, 77, 255, 12, 12, 12, 255]) };
    assert.equal(toGrayscale(grey).exact, true, 'true grayscale is exact');
});
